<?php

abstract class Field extends CComponent {

	/**
	 * Construct field
	 */
	public function __construct() {
		$this->type = strtolower(
            $this->key()
        );
		$this->name = $this->name();
	}

	/**
	 * Generate random identification number with bytes length
	 * @param string $prefix - Default prefix
	 * @param int $length - Length of generated bytes (x2 symbols)
	 * @return string - String with random id
	 * @throws CException
	 */
	public function getRandomName($prefix = "id-", $length = 5) {
		$r = Yii::app()->getSecurityManager()->generateRandomBytes($length, false);;
		if ($r === false) {
			throw new CException(openssl_error_string());
		}
		return $prefix.$r;
	}

    /**
     * Override that method to get current field instance
     * @param string $class - Name of field's class
     * @return Field - Field object
     */
    public static function field($class = null) {
		if ($class == null) {
			$class = get_called_class();
		}
        if (!isset(self::$_cached[$class])) {
            return (self::$_cached[$class] = new $class());
        } else {
            return self::$_cached[$class];
        }
    }

    private static $_cached = [];

	/**
	 * Render field with value or data
	 * @param CActiveForm $form - Active form for which we're rendering fields
	 * @param FormModel $model - Form's model with data configuration
	 * @return String - Just rendered field result
	 */
	public final function renderEx($form, $model) {
		return $this->render($form, $model);
	}

	/**
	 * Bind render parameters to field instance
	 * @param string $key - Unique key for field (identification value)
	 * @param string $label - Field's label
	 * @param mixed $value - Any value for field
	 * @param array $data - Array with values (for DropDown lists)
	 * @param array $options - Html options for field component
	 * @return Field - Field instance
	 */
	public function bind($key, $label = "", $value = null, $data = [], $options = []) {

		assert(is_string($label), "Label must be with String type");
		assert(is_string($key), "Key must be with String type");
		assert(is_array($data), "Data must be with Array type");
		assert(is_array($options), "Options must be with Array type");

		$this->label = $label;
		$this->key = $key;
		$this->value = $value;
		$this->data = $data;
		$this->options = $options;

		$this->options += [
			"id" => $key,
			"placeholder" => $label
		];

		return $this;
	}

	/**
	 * Render field with html options
	 * @param CActiveForm $form - Class with active form widget
	 * @param FormModel $model - Instance of database model
	 * @param string $key - Unique key
	 * @param array $options - Array with html options
	 * @return String - Just rendered content
	 */
	public function render2($form, $model, $key, $options) {
		return $this->bind($key, "", null, [], $options)->renderEx($form, $model);
	}

	/**
	 * Override that method to render field base on it's type
	 * @param CActiveForm $form - Form
	 * @param FormModel $model - Model
	 * @return String - Just rendered field result
	 */
	public abstract function render($form, $model);

	/**
	 * Override that method to return field's key
	 * @return String - Key
	 */
	public abstract function key();

	/**
	 * Override that method to return field's label
	 * @return String - Label
	 */
	public abstract function name();

	/**
	 * @return Mixed - Field's value (optional)
	 */
	public function getValue() {
		return $this->value;
	}

	/**
	 * @return String - Field's key name
	 */
	public function getKey() {
		return $this->key;
	}

	/**
	 * @return String - Field's label associated with key
	 */
	public function getName() {
		return $this->name;
	}

	/**
	 * @return Array - Array with data for DropDown list
	 */
	public function getData() {
		return $this->data;
	}

	/**
	 * @return String - Field's label
	 */
	public function getLabel() {
		return $this->label;
	}

	/**
	 * @return String - Field's type (unique key)
	 */
	public function getType() {
		return $this->type;
	}

	/**
	 * @return Array - Array with html options
	 */
	public function getOptions() {
		return $this->options;
	}

	private $value;
	private $key;
	private $type;
	private $name;
	private $data;
	private $label;
	private $options;
}